@startuml
title eClinic - Workflow

actor Owner
participant eClinic
actor Vet

Vet-> eClinic : 1. signIn()
activate eClinic
activate Vet

alt isUnauthorised
    Vet -> eClinic : 2.1. signUp()
    deactivate Vet
    eClinic -> eClinic: 2.2. setToken()
else isAuthorised
    eClinic -> eClinic: 3. setToken()
end
deactivate eClinic


Owner -> eClinic : 4. signIn()
activate eClinic
activate Owner

alt isUnauthorised
    Owner -> eClinic : 5.1. signUp()
    deactivate Owner
    eClinic <- eClinic: 5.2. setToken()
else isAuthorised
    eClinic <- eClinic: 6. setToken()
end
deactivate eClinic

opt
    Vet -> eClinic : 7. manageSchedule()
    activate eClinic
    activate Vet
    eClinic -> eClinic : 8. generateSlots()
    eClinic --> Vet : 9. showGeneratedSlots()
    deactivate eClinic
    deactivate Vet
end

loop UntilNotBookAppointment
    Owner -> eClinic : 10. openVets()
    activate eClinic
    activate Owner

    eClinic --> Owner : 11. showVets()

    opt
        Owner -> eClinic : 12. filterVets()
        eClinic --> Owner : 13. showVets()
    end

    opt
        Owner -> eClinic : 14. sortVets()
        eClinic --> Owner : 15. showVets()
    end

    opt
        Owner -> eClinic : 16. openVetSchedule()
        eClinic --> Owner : 17. showVetSchedule()
    end
end

Owner -> eClinic : 18. bookAppointment()
eClinic <- eClinic : 19. setApptStatus('scheduled')
eClinic -> Owner : 20. apptNotification('scheduled')
deactivate Owner
eClinic -> Vet : 21. apptNotification('scheduled')
deactivate eClinic

loop UntilStatusNotCompleted
    opt
        Owner -> eClinic : 22. viewApptStatus()
    end
end

eClinic -> Vet : 23. providePrice()
activate eClinic
eClinic -> Owner : 24. priceNotification()
deactivate eClinic

Vet -> eClinic : 25. setApptStatus('in progress')
activate Vet
activate eClinic
eClinic -> Owner : 26. apptNotification('in progress')
activate Owner

opt
    Vet -> eClinic : 27. updatePrice()
end

Vet -> eClinic : 28. setNotes()
Vet -> eClinic : 29. setResult()

opt
    Vet -> eClinic : 30. setDiagnosis()
end


alt OnlinePayment
    Owner -> eClinic : 31.1. payForAppointment('online')
    eClinic --> Owner : 31.2. paymentNotification('online')
    eClinic -> Vet : 31.3. paymentNotification('online')
else OfflineAndCard
    Owner -> Vet : 32. payForAppointment('offlineCard')
else OfflineAndCash
    Owner -> Vet: 33. payForAppointment('offlineCash')
end

Vet -> eClinic : 34. setApptStatus('completed')
deactivate Vet
eClinic -> Owner : 35. apptNotification('completed')
deactivate eClinic
deactivate Owner

opt
    Vet -> eClinic : 36. openAppointmentHistory()
    activate eClinic
    activate Vet
    eClinic --> Vet : 37. showAppointmentHistory()
    deactivate eClinic
    deactivate Vet
end

opt
    Owner -> eClinic : 38. openAppointmentHistory()
    activate eClinic
    activate Owner
    eClinic --> Owner: 39. showAppointmentHistory()
    deactivate eClinic
    deactivate Owner
end

destroy eClinic
@enduml